jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v4 # Configura pnpm
        with:
          version: 10 # o la versión que especifica tu packageManager

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm' # Cambia el cache a pnpm

      - run: pnpm install --frozen-lockfile # Usa pnpm para instalar
      - run: npx playwright install --with-deps # Esto puede seguir usando npx si es necesario
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t lint test build e2e # npx aquí debería funcionar bien después de pnpm install
